catalog:
  "@chromatic-com/storybook": "^5.1.1"
  "@storybook/addon-a11y": "^10.3.6"
  "@storybook/addon-docs": "^10.3.6"
  "@storybook/addon-svelte-csf": "^5.1.2"
  "@storybook/sveltekit": "^10.3.6"
  "@types/node": "^24"
  "storybook": "^10.3.6"
  "typescript": "^6.0.2"